# plan-9 mk mkfile

# things that are compiled and left as obj
src = siaddres sibldpol sicbreg sicbstat siclose siconnec siestabl \
	sigetadd siinit sinew sinewses sipoll sircv sireinit sisend \
	sisendt sisendu sisetsig sishutdo sisignal siterm siwait sigetname silisten \
	sitrash

headers = siconst socket_if sisetup sistruct


MKSHELL=ksh

CFLAGS = 
ALL = libsi.a

< ../master.mk
NUKE = $NUKE sitest

libs =  -L./ -lsi

${src:%=%.o}:       ${headers:%=%.h}
libsi.a(%.o):N:	%.o
libsi.a:    ${src:%=libsi.a(%.o)}
	(
		names="${newprereq//libsi.a\(}"                       # pluck off lib.*( from each in newprereq
		ar r $target ${names//\)/} #&& rm ${names//\)/}   # archive and remove after ditching trailing ) from each name
	)

$LIB_DIR/sdaniels:Q:
	if [[ ! -d $LIB_DIR/sdaniels ]]
	then
		mkdir -p $LIB_DIR/sdaniels
	fi

 $INC_DIR/sdaniels:Q:
	if [[ ! -d $INC_DIR/sdaniels ]]
	then
		mkdir -p $INC_DIR/sdaniels
	fi
	

# always out of date
publish:V: libsi.a  $INC_DIR $LIB_DIR
	cp libsi.a $LIB_DIR/sdaniels/
	cp socket_if.h $INC_DIR/sdaniels/

sitest:: sitest.o libsi.a
	cc $CFLAGS sitest.c -L. -lsi  -o sitest
